### PR TITLE
First version of 3D model of our car.

### PR DESCRIPTION
**Pull request by Anthony1911**
Model for designing the car, created in SketchUP. It will be updated as we add more hardware elements to our car.

### CODE REVIEW

**Review by pontuslae — CHANGES_REQUESTED** [review]
Please add one or more picture file(s) so it is viewable online without requiring a 3d modelling software.

**Comment by pontuslae** [comment]
Update one or more picture file(s) so it is viewable online. And you don't need a 3d modelling software. @Anthony1911

**Comment by timjon** [comment]
Cant check it

**Comment by timjon** [comment]
Cant check the file

**Review by pontuslae — APPROVED** [review]
Looks good. A change of font wouldn't hurt though.

**Comment by timjon** [comment]
Do we want sensors added to the model?

**Review by timjon — DISMISSED** [review]
Doesnt have any sensors

**Pull request merged**
